### ISSUE TITLE
Invalid jpeg generated

### ISSUE THREAD

**Issue by Biboba** [nodeca/glur#2]
Hello,

Thanks for the library.
I am trying to save the Uint8Array blurred data output from glur to a jpeg file but I have an error "SOI not found" (Start of file) as it is looking for a specific value:
http://www.file-recovery.com/jpg-signature-format.htm

I believe some values in the array should not be "blurred".

Thanks

**Comment by puzrin** [comment]
Glur works with raw RGBA data. That' not related to jpeg anyhow.

If you need jpeg, you may draw RGBA to canvas, and that use `.toBlob()` method.
